on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
      - uses: actions/checkout@v4
      - name: Composer install
        run: |
          composer install
      - name: Build phar
        run: |
          composer run build-phar
      - uses: actions/upload-artifact@v4
        with:
          name: release-schedule.phar
          path: release-schedule.phar

  release-on-push:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          # this is necessary if the release creation also needs to trigger workflows
          # token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: php
      - name: Download artifact
        uses: actions/download-artifact@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: release-schedule.phar
      - name: Upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} release-schedule.phar
