on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
      - name: Composer install
        run: |
          composer install
      - name: Build phar
        run: |
          composer run build-phar
      - uses: actions/upload-artifact@v4
        with:
          name: release-schedule.phar
          path: release-schedule.phar

  release-on-push:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-schedule.phar
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "${{ steps.release.outputs.upload_url }}" \
            --data-binary "@release-schedule.phar"
